name = "lm-system-api"
main = "workers/api.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "portal.lucasmorenopersonal.com.br/api/*", zone_name = "lucasmorenopersonal.com.br" }
]

[vars]
ADMIN_TOKEN = "admin4191luc"
PORTAL_ADMIN_TOKEN = "admin4191luc"

[[d1_databases]]
binding = "DB"
database_name = "lmsystemv2-db"
database_id = "1de90532-157b-473e-8e7a-655ca9e0953d"