import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import worker, { initializeSchemaForTests } from '../workers/api.js';
import { SqliteD1 } from './helpers/sqlite-d1.mjs';

const ENV={ADMIN_TOKEN:'admin-token',PREMIUM_PROFESSIONAL_WORKSPACE_ENABLED:'true'};
async function withDb(run){const dir=await mkdtemp(join(tmpdir(),'nutrition-parity-'));const db=new SqliteD1(join(dir,'test.db'));try{await initializeSchemaForTests(db);await run(db);}finally{db.close();await rm(dir,{recursive:true,force:true});}}
async function http(db,method,path,body,{student,admin=true}={}){const headers={'content-type':'application/json'};if(student){headers['x-student-email']=student.email;headers['x-student-token']=student.token;}else if(admin)headers['x-admin-token']=ENV.ADMIN_TOKEN;const response=await worker.fetch(new Request(`https://portal.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),{DB:db,...ENV});return{status:response.status,body:await response.json()};}
async function createStudent(db,name){const email=`${name}@example.test`;const created=await http(db,'POST','/api/admin/premium/workspace/students',{name,email,whatsapp:'11999999999'});assert.equal(created.status,201);const student={id:created.body.data.studentId,email,token:created.body.data.token};await db.prepare("UPDATE premium_students SET consultation_status='ACTIVE' WHERE student_id=?").bind(student.id).run();return student;}
const payload=(version)=>({title:`Plano V${version} Canário`,goal:`Objetivo V${version}`,strategy:`Estratégia V${version}`,meals:[{name:`Café da manhã V${version}`,time:'07:00',guidance:`Direção V${version}`,primary_text:`Ovos V${version}`,items:[{food:`Fruta V${version}`,quantity:'1',unit:'unidade',note:`Nota V${version}`}],substitutions:[{text:`Troca refeição V${version}`}]}],substitutions:[{text:`Troca plano V${version}`}],adherence_rules:[`Regra de adesão V${version}`],notes:`Observação V${version}`,whatsapp_message:`Suporte V${version}`});
async function createDraft(db,student,plan){const response=await http(db,'POST',`/api/admin/premium/students/${student.id}/nutrition-plan/draft`,{plan});assert.equal(response.status,200);return response.body.data;}
async function publish(db,student,draft){const response=await http(db,'POST',`/api/admin/premium/nutrition-plans/${draft.id}/publish`,{student_id:student.id});assert.equal(response.status,200);return response.body.data;}
async function current(db,student){return http(db,'GET','/api/portal/premium/nutrition-plan/current',undefined,{student});}

function assertVersion(plan,version){assert.equal(plan.title,`Plano V${version} Canário`);assert.equal(plan.goal,`Objetivo V${version}`);assert.equal(plan.strategy,`Estratégia V${version}`);assert.equal(plan.meals[0].name,`Café da manhã V${version}`);assert.equal(plan.meals[0].time,'07:00');assert.equal(plan.meals[0].guidance,`Direção V${version}`);assert.equal(plan.meals[0].primary_text,`Ovos V${version}`);assert.deepEqual(plan.meals[0].items,[{food:`Fruta V${version}`,quantity:'1',unit:'unidade',note:`Nota V${version}`}]);assert.deepEqual(plan.meals[0].substitutions,[{text:`Troca refeição V${version}`}]);assert.deepEqual(plan.substitutions,[{text:`Troca plano V${version}`}]);assert.deepEqual(plan.adherence_rules,[`Regra de adesão V${version}`]);assert.equal(plan.observations,`Observação V${version}`);assert.equal(plan.notes,`Observação V${version}`);assert.equal(plan.status,'PUBLISHED');assert.equal(plan.version_number,version);assert.ok(plan.published_at);assert.equal(plan.updated_at,plan.published_at);for(const privateField of ['student_id','student_email','published_by','source_feedback_id'])assert.equal(privateField in plan,false);}

test('professional draft → published current → student preserves the complete public V1/V2 contract',async()=>withDb(async db=>{const student=await createStudent(db,'canary');const other=await createStudent(db,'other');assert.deepEqual((await current(db,student)).body.data,null);
 const v1=await createDraft(db,student,payload(1));await publish(db,student,v1);assertVersion((await current(db,student)).body.data,1);assert.equal((await current(db,other)).body.data,null,'identity-derived current never leaks another student plan');
 const v2=await createDraft(db,student,payload(2));const whileDraft=await current(db,student);assertVersion(whileDraft.body.data,1);assert.doesNotMatch(JSON.stringify(whileDraft.body),'V2');
 await publish(db,student,v2);assertVersion((await current(db,student)).body.data,2);const history=await http(db,'GET',`/api/admin/premium/students/${student.id}/nutrition-plan/history`);assert.equal(history.status,200);assert.deepEqual(history.body.data.map(row=>[row.version_number,row.status]),[[2,'PUBLISHED'],[1,'ARCHIVED']]);
 await http(db,'POST',`/api/admin/premium/workspace/students/${student.id}/deactivate`,{});assert.equal((await current(db,student)).status,403);await http(db,'POST',`/api/admin/premium/workspace/students/${student.id}/reactivate`,{});assertVersion((await current(db,student)).body.data,2);
}));

test('official Home/menu journey and deployed renderer consume every canonical student field',()=>{for(const file of ['portal-premium-home.html','public/portal-premium-home.html','portal-shared.js','public/portal-shared.js','public/assets/js/lm-access.js']){const source=fs.readFileSync(file,'utf8');assert.match(source,/portal-premium-nutrition-plan\.html/);assert.doesNotMatch(source,/portal-plano-alimentar\.html/);}for(const file of ['public/portal-premium-nutrition-plan.js','public/assets/js/portal-premium-nutrition-plan.js']){const source=fs.readFileSync(file,'utf8');for(const field of ['title','goal','strategy','meals','guidance','substitutions','observations','hydration','supplements','adherence_rules','updated_at'])assert.match(source,new RegExp(`plan\\.${field}|meal\\.${field}`),`${file} renders ${field}`);assert.match(source,/api\('\/portal\/premium\/nutrition-plan\/current'\)/);}});
