import test from 'node:test'; import assert from 'node:assert/strict';
import { NUTRITION_PLAN_STATUS, canEditNutritionPlan, isLifecycleCompatible } from '../workers/premium/domain/nutrition-plan-status.js';
import { validateNutritionPlanDraftStructure, validateNutritionPlanStructure, toCanonicalNutritionPlan } from '../workers/premium/domain/nutrition-plan-schema.js';
import { createUpdateNutritionPlanDraftUseCase } from '../workers/premium/application/update-nutrition-plan-draft.js';
test('nutrition plan lifecycle states and draft editability',()=>{ assert.deepEqual(Object.values(NUTRITION_PLAN_STATUS), ['DRAFT','PUBLISHED','ARCHIVED']); assert.equal(canEditNutritionPlan({status:'DRAFT'}), true); assert.equal(canEditNutritionPlan({status:'PUBLISHED'}), false); assert.equal(isLifecycleCompatible({status:'ARCHIVED',is_active:1}), false); });
test('canonical schema validates structure but not clinical content',()=>{ const result=validateNutritionPlanStructure({title:'Plano', meals:[{id:'m1',name:'Café',items:[{food:'Item',quantity:'1',unit:'un'}]}]}); assert.equal(result.ok,true); assert.equal(toCanonicalNutritionPlan(result.plan).meals[0].items[0].food,'Item'); assert.equal(validateNutritionPlanStructure({title:'',meals:[]}).ok,false); });
test('draft schema accepts incomplete content but rejects invalid collection types',()=>{assert.equal(validateNutritionPlanDraftStructure({title:'',meals:[]}).ok,true);assert.equal(validateNutritionPlanDraftStructure({meals:[{name:'',items:[]}]}).ok,true);for(const [input,error] of [[{meals:'texto'},'MEALS_MUST_BE_ARRAY'],[{meals:{}},'MEALS_MUST_BE_ARRAY'],[{substitutions:42},'SUBSTITUTIONS_MUST_BE_ARRAY'],[{meals:[{items:'texto'}]},'MEAL_1_ITEMS_MUST_BE_ARRAY'],[{meals:[{items:[{substitutions:{}}]}]},'MEAL_1_ITEM_1_SUBSTITUTIONS_MUST_BE_ARRAY']]){const result=validateNutritionPlanDraftStructure(input);assert.equal(result.ok,false);assert.ok(result.errors.includes(error));}});
test('published plan validation remains strict after permissive draft validation',()=>{assert.equal(validateNutritionPlanDraftStructure({title:'',meals:[]}).ok,true);assert.equal(validateNutritionPlanStructure({title:'',meals:[]}).ok,false);});
test('draft update reports invalid draft structures consistently',async()=>{const useCase=createUpdateNutritionPlanDraftUseCase({nutritionPlanRepository:{findById:async()=>({id:'draft-1',student_id:'student-1',status:'DRAFT'}),updateDraft:async()=>{throw new Error('should not update');}}});const result=await useCase.execute({id:'draft-1',student_id:'student-1',updates:{expected_updated_at:'2026-01-01T00:00:00Z',meals:'texto'}});assert.equal(result.ok,false);assert.equal(result.error,'INVALID_DRAFT_STRUCTURE');assert.deepEqual(result.details,['MEALS_MUST_BE_ARRAY']);});
