import test from 'node:test';import assert from 'node:assert/strict';
import path from 'node:path';import {fileURLToPath} from 'node:url';
import {aggregateRuns,classifyRun,normalizeRunHttpFailures} from '../scripts/lib/portal-performance-core.mjs';
import {analysisMarkdown,analyzePerformanceReport,buildPerformanceSource,delta,exitCodeForAnalysis,EXPECTED_PAGES,METRICS,sanitizeSelectorValue,validatePerformanceReport} from '../scripts/lib/portal-performance-analysis.mjs';
import {startLocalServer} from '../scripts/lib/portal-performance-server.mjs';
const A='a'.repeat(40),B='b'.repeat(40),C='c'.repeat(40),D='d'.repeat(40);
const rect={x:0,y:0,width:10,height:10,top:0,right:10,bottom:10,left:0};
function source(kind='local'){if(kind==='pull_request')return{baseSha:A,headSha:B,checkoutSha:C,workflowSha:D,canonicalMainSha:null,ref:'refs/pull/400/merge',eventName:'pull_request',nodeVersion:'v22.0.0',chromeVersion:'Chrome/150'};if(kind==='main')return{baseSha:C,headSha:C,checkoutSha:C,workflowSha:C,canonicalMainSha:C,ref:'refs/heads/main',eventName:'workflow_dispatch',nodeVersion:'v22.0.0',chromeVersion:'Chrome/150'};if(kind==='branch')return{baseSha:null,headSha:B,checkoutSha:C,workflowSha:C,canonicalMainSha:null,ref:'refs/heads/feature',eventName:'workflow_dispatch',nodeVersion:'v22.0.0',chromeVersion:'Chrome/150'};return{baseSha:null,headSha:C,checkoutSha:C,workflowSha:null,canonicalMainSha:null,ref:'local',eventName:'local',nodeVersion:'v22.0.0',chromeVersion:'Chrome/150'}}
function fixture(status='MEASURED',sourceKind='local'){const makeRun=(page,scenario,index)=>{const cold=scenario==='COLD',last=page===EXPECTED_PAGES.at(-1);const metrics=Object.fromEntries(METRICS.map(key=>[key,key==='cls'?(page.includes('home')&&cold?.33:0):key==='failedRequestCount'||key==='longTaskCount'||key==='longTaskDuration'?0:key==='requestCount'?2:(cold?100:50)+(last?1000:0)]));return{run:index,page,scenario,metrics,resources:[{url:'/portal.css',type:'stylesheet',transferBytes:cold?10:0,decodedBodyBytes:20,fromCache:!cold,status:200},{url:last?'/largest.js':`/${page.slice(1)}.js`,type:'script',transferBytes:last?1000:1,decodedBodyBytes:last?1200:2,fromCache:false,status:200}],failedRequests:[],layoutShiftEvents:page.includes('home')&&cold?[{startTime:index,value:.33,hadRecentInput:false,sources:index===2?null:index===3?[]:[{nodeSelector:'main>div.card',previousRect:{...rect},currentRect:{...rect}}]}]:[],mainDocumentLoaded:true,externalRequestAttempted:false,completionStatus:status}};const pages=EXPECTED_PAGES.map(page=>({page,scenarios:['COLD','WARM'].map(scenario=>{const runs=Array.from({length:5},(_,i)=>makeRun(page,scenario,i+1));return{scenario,runs,aggregate:aggregateRuns(runs)}})}));return{schemaVersion:'1.0.0',environment:'LAB_STUBBED',source:source(sourceKind),profile:{schemaVersion:'1.0.0',runs:5,scenarios:['COLD','WARM'],pages:EXPECTED_PAGES,viewport:{},network:{},cpuSlowdownMultiplier:1},pages,warnings:[],status}}

test('proveniência explícita cobre PR, dispatch main/branch e local',()=>{for(const kind of ['pull_request','main','branch','local'])assert.doesNotThrow(()=>validatePerformanceReport(fixture('MEASURED',kind)));assert.notEqual(source('pull_request').workflowSha,source('pull_request').headSha);assert.equal(source('pull_request').canonicalMainSha,null);assert.equal(analyzePerformanceReport(fixture()).source.checkoutSha,C)});
test('produtor deriva proveniência sem variável GitHub inexistente',()=>{assert.deepEqual(buildPerformanceSource({checkoutSha:C,chromeVersion:'Chrome/150',nodeVersion:'v22.0.0',env:{}}),source('local'));const pr=buildPerformanceSource({checkoutSha:C,chromeVersion:'Chrome/150',nodeVersion:'v22.0.0',env:{PERFORMANCE_EVENT_NAME:'pull_request',PERFORMANCE_REF:'refs/pull/400/merge',PERFORMANCE_BASE_SHA:A,PERFORMANCE_HEAD_SHA:B,GITHUB_SHA:D,PERFORMANCE_CHECKOUT_SHA:C}});assert.deepEqual(pr,source('pull_request'));assert.throws(()=>buildPerformanceSource({checkoutSha:C,env:{PERFORMANCE_CHECKOUT_SHA:A}}),/checkoutSha/)});
test('source ausente, SHA inválido e fallback legado são proibidos',()=>{for(const mutate of [r=>delete r.source.headSha,r=>r.source.headSha='abc',r=>{r.source={sha:C};}]){const r=fixture();mutate(r);assert.throws(()=>validatePerformanceReport(r),/source|SHA/)}});
test('inventário exato rejeita página/cenário duplicado ou inesperado',()=>{for(const mutate of [r=>r.pages[1].page=r.pages[0].page,r=>r.pages[0].page='/unexpected',r=>r.pages[0].scenarios[1].scenario='COLD']){const r=fixture();mutate(r);assert.throws(()=>validatePerformanceReport(r),/páginas|cenários/)}});
test('runs 1–5, page/scenario e aggregate são verificados',()=>{for(const mutate of [r=>r.pages[0].scenarios[0].runs[4].run=4,r=>r.pages[0].scenarios[0].runs[0].page='/wrong',r=>r.pages[0].scenarios[0].runs[0].scenario='WARM',r=>r.pages[0].scenarios[0].aggregate.lcp.p75++]){const r=fixture();mutate(r);assert.throws(()=>validatePerformanceReport(r),/runs|run|aggregate/)}});
test('INCOMPLETE/FAILED geram P0 e análise MEASURED não gera P0',()=>{for(const status of ['INCOMPLETE','FAILED'])assert.ok(analyzePerformanceReport(fixture(status)).findings.some(x=>x.priority==='P0'));assert.equal(analyzePerformanceReport(fixture()).findings.some(x=>x.priority==='P0'),false)});
test('exit code exige MEASURED nesta sprint',()=>{assert.equal(exitCodeForAnalysis('MEASURED'),0);assert.equal(exitCodeForAnalysis('INCOMPLETE'),1);assert.equal(exitCodeForAnalysis('FAILED'),1)});
test('delta absoluto/percentual preserva null e não divide por zero',()=>{assert.deepEqual(delta(100,50),{absolute:50,percentage:100});assert.deepEqual(delta(5,0),{absolute:5,percentage:null});assert.deepEqual(delta(null,1),{absolute:null,percentage:null})});
test('ranking global põe maior recurso da última página primeiro e agrega compartilhado',()=>{const a=analyzePerformanceReport(fixture());assert.equal(a.globalResourceRanking[0].url,'/largest.js');const css=a.globalResourceRanking.find(x=>x.url==='/portal.css'&&x.scenario==='COLD');assert.equal(css.pageCount,5);assert.equal(css.requestOccurrences,25);assert.equal(css.totalObservedTransferBytes,250);const warm=a.globalResourceRanking.find(x=>x.url==='/portal.css'&&x.scenario==='WARM');assert.equal(warm.totalObservedTransferBytes,0);assert.equal(warm.cacheHitCount,25)});
test('ranking global preserva null e desempata por URL',()=>{const r=fixture();for(const p of r.pages)for(const s of p.scenarios)for(const run of s.runs)run.resources.push({url:'/null.js',type:'script',transferBytes:null,decodedBodyBytes:null,fromCache:false,status:200});for(const p of r.pages)for(const s of p.scenarios)s.aggregate=aggregateRuns(s.runs);const a=analyzePerformanceReport(r);assert.equal(a.globalResourceRanking.find(x=>x.url==='/null.js').totalObservedTransferBytes,null);const ties=a.globalResourceRanking.filter(x=>x.totalObservedTransferBytes===5).map(x=>x.url);assert.deepEqual(ties,[...ties].sort())});
test('pageRanking contém cinco páginas e rankings por métrica com null no fim',()=>{const r=fixture();const last=r.pages.at(-1),cold=last.scenarios.find(x=>x.scenario==='COLD');for(const run of cold.runs)run.metrics.cls=5;cold.aggregate=aggregateRuns(cold.runs);const first=r.pages[0].scenarios[0];for(const run of first.runs)run.metrics.lcp=null;first.aggregate=aggregateRuns(first.runs);const a=analyzePerformanceReport(r);assert.equal(a.pageRanking.pages.length,5);assert.equal(a.pageRanking.byColdTransfer[0].page,EXPECTED_PAGES.at(-1));assert.equal(a.pageRanking.byColdLcp.at(-1).page,EXPECTED_PAGES[0]);assert.equal(a.pageRanking.byColdCls[0].page,EXPECTED_PAGES.at(-1));assert.equal(a.pageRanking.byRequests.map(x=>x.page).join(),[...EXPECTED_PAGES].sort().join())});
test('Markdown tem títulos correspondentes e é determinístico',()=>{const a=analyzePerformanceReport(fixture()),md=analysisMarkdown(a);for(const title of ['Ranking por transferência COLD','Ranking por LCP COLD','Ranking por CLS COLD','Ranking por quantidade de requests COLD','Ranking global de recursos'])assert.match(md,new RegExp(title));assert.equal(md,analysisMarkdown(a));assert.match(md,/Nenhuma otimização foi autorizada/)});
test('layout valida evento, rects e números',()=>{for(const mutate of [e=>delete e.hadRecentInput,e=>e.value=-1,e=>e.startTime=Infinity,e=>e.sources[0].previousRect.extra=1,e=>e.sources[0].currentRect.x=NaN]){const r=fixture(),e=r.pages[1].scenarios[0].runs[0].layoutShiftEvents[0];mutate(e);assert.throws(()=>validatePerformanceReport(r),/layout/)}});
test('consumidor sanitiza selector seguro e descarta PII, HTML e excesso',()=>{assert.equal(sanitizeSelectorValue('main>div.card'),'main>div.card');for(const value of ['ana@example.com','token-secret','student-1','aluno-1','<div>texto</div>','x'.repeat(241)])assert.equal(sanitizeSelectorValue(value),null);const r=fixture(),events=r.pages[1].scenarios[0].runs;events[0].layoutShiftEvents[0].sources.push({nodeSelector:'ana@example.com',previousRect:null,currentRect:null});events[3].layoutShiftEvents[0].sources=null;const a=analyzePerformanceReport(r),md=analysisMarkdown(a);assert.deepEqual(a.layoutShiftSummary,{totalLayoutShiftEvents:5,eventsWithSources:2,eventsWithoutSources:3,sourcesSanitized:2,sourcesDiscarded:1});assert.doesNotMatch(md,/ana@example|token-secret|student-1/);assert.match(md,/sem sources: 3/)});
test('resource e failedRequest inválidos são rejeitados',()=>{const r=fixture();r.pages[0].scenarios[0].runs[0].resources[0].transferBytes='10';assert.throws(()=>validatePerformanceReport(r),/resource/);const q=fixture();q.pages[0].scenarios[0].runs[0].failedRequests=[{url:'/api/x'}];assert.throws(()=>validatePerformanceReport(q),/failedRequest/)});
test('favicon 404 somente em resources cria observedHttpFailures, P0 e status não aprovado',()=>{const r=fixture(),run=r.pages[0].scenarios[0].runs[0];run.resources.push({url:'/favicon.ico',type:'other',resourceType:'Other',transferBytes:0,decodedBodyBytes:0,fromCache:false,status:404});const a=analyzePerformanceReport(r);assert.equal(a.status,'INCOMPLETE');assert.deepEqual(a.observedHttpFailures[0],{page:EXPECTED_PAGES[0],scenario:'COLD',run:1,url:'/favicon.ico',status:404,resourceType:'Other',source:'resources'});assert.ok(a.findings.some(x=>x.priority==='P0'&&x.comparator==='/favicon.ico'));assert.equal(exitCodeForAnalysis(a.status),1);assert.match(analysisMarkdown(a),/`\/favicon\.ico` — HTTP 404/)});
test('falha presente em resources e failedRequests é deduplicada como both',()=>{const run={page:'/p',scenario:'WARM',run:2,resources:[{url:'/favicon.ico',status:404,type:'image'}],failedRequests:[{url:'/favicon.ico',status:404,resourceType:'Image',reason:'HTTP 404'}]};assert.deepEqual(normalizeRunHttpFailures(run),[{page:'/p',scenario:'WARM',run:2,url:'/favicon.ico',status:404,resourceType:'image',source:'both'}])});
test('normalização cobre tipos locais, 4xx/5xx e ignora 200/null',()=>{for(const [url,type,status] of [['/a.js','script',404],['/a.css','stylesheet',404],['/a.png','image',404],['/api/x','xhr',404],['/','document',404],['/font.woff2','font',500]]){const failures=normalizeRunHttpFailures({resources:[{url,type,status}],failedRequests:[]});assert.equal(failures.length,1);assert.equal(failures[0].status,status)}assert.deepEqual(normalizeRunHttpFailures({resources:[{url:'/ok',type:'other',status:200},{url:'/unknown',type:'other',status:null}],failedRequests:[]}),[])});
test('falhas HTTP são ordenadas deterministicamente',()=>{const failures=normalizeRunHttpFailures({page:'/z',scenario:'COLD',run:3,resources:[{url:'/z',type:'other',status:500},{url:'/a',type:'other',status:404}],failedRequests:[]});assert.deepEqual(failures.map(x=>x.url),['/a','/z'])});
test('classifyRun torna documento inválido FAILED e recurso/API inválido INCOMPLETE',()=>{const base={metrics:{},failedRequests:[],mainDocumentStatus:200,mainDocumentLoaded:true,loadEventFired:true,resources:[]};assert.equal(classifyRun({...base,resources:[{url:'/x.js',type:'script',status:404}]}).completionStatus,'INCOMPLETE');assert.equal(classifyRun({...base,resources:[{url:'/api/x',type:'xhr',status:404}]}).completionStatus,'INCOMPLETE');assert.equal(classifyRun({...base,resources:[{url:'/',type:'document',status:404}]}).completionStatus,'FAILED')});
test('stub retorna notifications 200, favicon 204, método 405 e desconhecido 404',async()=>{const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../public'),server=await startLocalServer(root);try{const base=`http://127.0.0.1:${server.port}`;let response=await fetch(base+'/api/portal/notifications/unread-count');assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,data:{count:0}});assert.equal((await fetch(base+'/favicon.ico')).status,204);response=await fetch(base+'/api/portal/notifications/unread-count',{method:'POST'});assert.equal(response.status,405);assert.equal((await fetch(base+'/api/unknown')).status,404);assert.doesNotMatch(JSON.stringify(server.requests),/@|token|Aluno/)}finally{await server.close()}});
