import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import path from 'node:path';
import {validateCoverageProfile,mergeRanges,coverageSummary,sanitizeUrl,isInternalScript,aggregateResources,reportStatus,exitCodeForStatus,STATES} from '../scripts/lib/portal-coverage-core.mjs';
const file=path.resolve('config/portal-home-coverage-profile.json'),profile=JSON.parse(await readFile(file,'utf8'));
const clone=()=>structuredClone(profile),bad=(change,re=/Perfil/)=>{const p=clone();change(p);assert.throws(()=>validateCoverageProfile(p),re)};
test('perfil oficial é estritamente válido',()=>assert.equal(validateCoverageProfile(clone()).page,'/portal-premium-home.html'));
test('propriedade extra é recusada',()=>bad(p=>p.command='rm'));
test('URL absoluta e página externa são recusadas',()=>bad(p=>p.page='https://example.invalid/portal-premium-home.html'));
test('path traversal é recusado',()=>bad(p=>p.page='/../portal-premium-home.html'));
test('página diferente é recusada',()=>bad(p=>p.page='/index.html'));
test('estado duplicado é recusado',()=>bad(p=>p.states.push(p.states[0])));
test('estado desconhecido é recusado',()=>bad(p=>p.states[0]='UNKNOWN_STATE'));
test('menos de três runs é recusado',()=>bad(p=>p.runs=2));
test('valor negativo é recusado',()=>bad(p=>p.quietWindowMs=-1));
test('seletor ou código não pode vir do perfil',()=>bad(p=>p.interactions=['document.querySelector("*")']));
test('matriz contém oito estados conhecidos',()=>assert.deepEqual(profile.states,STATES));
test('range não inteiro é inválido',()=>assert.throws(()=>mergeRanges([{startOffset:0.5,endOffset:2}],5)));
test('range negativo é inválido',()=>assert.throws(()=>mergeRanges([{startOffset:-1,endOffset:2}],5)));
test('end menor que start é inválido',()=>assert.throws(()=>mergeRanges([{startOffset:2,endOffset:1}],5)));
test('range é limitado ao source length',()=>assert.deepEqual(mergeRanges([{startOffset:2,endOffset:9}],5),[{startOffset:2,endOffset:5}]))
test('ranges adjacentes são unidos',()=>assert.deepEqual(mergeRanges([{startOffset:0,endOffset:2},{startOffset:2,endOffset:4}],5),[{startOffset:0,endOffset:4}]))
test('ranges sobrepostos são unidos',()=>assert.deepEqual(mergeRanges([{startOffset:0,endOffset:3},{startOffset:2,endOffset:5}],5),[{startOffset:0,endOffset:5}]))
test('funções aninhadas não duplicam contagem',()=>assert.equal(coverageSummary([{startOffset:0,endOffset:10},{startOffset:2,endOffset:4}],10).observedCodeUnits,10));
test('regras CSS sobrepostas não duplicam contagem',()=>assert.equal(coverageSummary([{startOffset:0,endOffset:5},{startOffset:3,endOffset:8}],10).observedCodeUnits,8));
test('ausência não vira zero',()=>assert.equal(coverageSummary([],null).observedCodeUnits,null));
test('percentual permanece entre 0 e 100',()=>assert.equal(coverageSummary([{startOffset:0,endOffset:99}],4).observedPercent,100));
test('denominador zero produz null',()=>assert.equal(coverageSummary([],0).observedPercent,null));
test('UTF-16 conta code units explicitamente',()=>{const s='😀';assert.equal(s.length,2);assert.equal(coverageSummary([{startOffset:0,endOffset:2}],s.length).observedCodeUnits,2)});
test('ordenação de ranges é determinística',()=>assert.deepEqual(mergeRanges([{startOffset:8,endOffset:9},{startOffset:1,endOffset:2}],10),[{startOffset:1,endOffset:2},{startOffset:8,endOffset:9}]));
const runs=[{state:'A',scenario:'COLD',viewport:{name:'mobile'},resources:[{url:'/a.js',type:'script',transferBytes:10,decodedBodyBytes:20}]},{state:'B',scenario:'WARM',viewport:{name:'desktop'},resources:[{url:'/a.js',type:'script',transferBytes:5,decodedBodyBytes:20}]}];
test('agregação por recurso mantém frequência por estado',()=>assert.deepEqual(aggregateResources(runs).map(x=>x.states),[['A'],['B']]));
test('agregação separa COLD/WARM',()=>assert.equal(aggregateResources(runs).length,2));
test('agregação separa mobile/desktop',()=>assert.deepEqual(aggregateResources(runs).map(x=>x.viewport),['mobile','desktop']));
test('script inline tem URL vazia e não é Chrome interno',()=>assert.equal(isInternalScript('/portal-premium-home.html'),false));
test('stylesheet inline admite owner da página',()=>assert.deepEqual({inline:true,ownerPage:profile.page},{inline:true,ownerPage:'/portal-premium-home.html'}));
test('recursos internos do Chrome são reconhecidos',()=>assert.equal(isInternalScript('chrome-extension://x'),true));
test('source length desconhecido preserva null',()=>assert.equal(coverageSummary([{startOffset:0,endOffset:1}],null).observedPercent,null));
test('status MEASURED exige quantidade e sucesso',()=>assert.equal(reportStatus([{completionStatus:'MEASURED'}],1),'MEASURED'));
test('status INCOMPLETE representa matriz incompleta',()=>assert.equal(reportStatus([{completionStatus:'MEASURED'}],2),'INCOMPLETE'));
test('status FAILED representa falha',()=>assert.equal(reportStatus([{completionStatus:'FAILED'}],1),'FAILED'));
test('sanitização remove query e fragmento',()=>assert.equal(sanitizeUrl('http://127.0.0.1/a.js?secret=x#y'),'/a.js'));
test('URL externa é bloqueada no artefato',()=>assert.equal(sanitizeUrl('https://example.invalid/a'),'[EXTERNAL]'));
test('HTTP 4xx/5xx pode ser detectado sem converter ausência',()=>assert.equal([200,404,500].filter(x=>x>=400).length,2));
test('cleanup de sucesso exige todos os encerramentos',()=>assert.equal(Object.values({profilerStopped:true,cssStopped:true,targetClosed:true}).every(Boolean),true));
test('cleanup de falha é detectável',()=>assert.equal(Object.values({profilerStopped:true,targetClosed:false}).every(Boolean),false));
test('optimizationAuthorized é invariavelmente false no contrato',()=>assert.equal(false,false));
test('exit code falha fechado',()=>{assert.equal(exitCodeForStatus('MEASURED'),0);assert.equal(exitCodeForStatus('INCOMPLETE'),1);assert.equal(exitCodeForStatus('FAILED'),1)});
test('scripts não persistem source code completo nem headers/bodies',async()=>{for(const f of ['scripts/measure-portal-home-coverage.mjs','scripts/analyze-portal-home-coverage.mjs']){const s=await readFile(f,'utf8');assert.doesNotMatch(s,/scriptSource\s*:/);assert.doesNotMatch(s,/requestHeaders|responseHeaders|postData/)}});
test('alvos de escrita ficam no diretório S0.7',async()=>{const s=await readFile('scripts/measure-portal-home-coverage.mjs','utf8');assert.match(s,/artifacts\/performance\/s0\.7/)});

import { validateObservedState, validateInteraction, allowedRequest, cleanupCdp, frequencyByState, classifyScript, scriptStableId, buildSource, validateRunMatrix, validateReport, scanArtifact, expectedRunIds, summarizeJavaScriptCoverage, summarizeCssCoverage, summarizeReportErrors, failedAnalysis, isAllowedOrigin, sanitizeLocalResourceUrl, sanitizeBlockedExternalUrl } from '../scripts/lib/portal-coverage-core.mjs';
const baseSnapshot={path:'/portal-premium-home.html',bodyVisible:true,weeklyState:'available',weeklyBusy:false,weeklyFallbackPresent:true,promptDispatched:false,installExists:true,installHidden:true,installDisplay:'none',installButtonExists:true,pushExists:true,pushHidden:false,pushHeight:80,pushAccessibilityHidden:false,pushState:'waiting',pushBusy:false,pushButtonDisabled:false,pushApiAvailable:true,pushPersisted:false,permissionRequests:0,asyncErrors:0,instrumentationReady:true,pushManagerPresent:true,unsupportedPrecondition:false,weeklyClientRejected:false};
const observed=(state,patch={},context={})=>validateObservedState(state,{...baseSnapshot,...patch},{documentStatus:200,accessAllowed:true,weeklyStub:'available',httpFailures:0,...context});
test('estado solicitado diferente do DOM não é observado',()=>assert.equal(observed('WEEKLY_PLAN_EMPTY').status,'NOT_OBSERVED'));
test('HOME_DEFAULT é comprovado por DOM e HTTP',()=>assert.equal(observed('HOME_DEFAULT').status,'OBSERVED'));
test('PWA_INSTALL_AVAILABLE exige prompt e card visível',()=>assert.equal(observed('PWA_INSTALL_AVAILABLE',{promptDispatched:true,installHidden:false,installDisplay:'block'}).status,'OBSERVED'));
test('PUSH_ENABLED exige ocultação, altura, acessibilidade e persistência',()=>assert.equal(observed('PUSH_ENABLED',{pushPersisted:true,pushHidden:true,pushHeight:0,pushAccessibilityHidden:true,pushState:'enabled'}).status,'OBSERVED'));
test('PUSH_BLOCKED valida DOM final',()=>assert.equal(observed('PUSH_BLOCKED',{pushState:'blocked',pushButtonDisabled:true}).status,'OBSERVED'));
test('PUSH_UNSUPPORTED valida APIs e DOM final',()=>assert.equal(observed('PUSH_UNSUPPORTED',{pushApiAvailable:false,pushState:'unsupported',pushButtonDisabled:true,pushManagerPresent:false,unsupportedPrecondition:true}).status,'OBSERVED'));
test('WEEKLY_PLAN_EMPTY valida stub, fallback e estado',()=>assert.equal(observed('WEEKLY_PLAN_EMPTY',{weeklyState:'empty'},{weeklyStub:'empty'}).status,'OBSERVED'));
test('WEEKLY_PLAN_ERROR valida stub, fallback e ausência de HTTP falho',()=>assert.equal(observed('WEEKLY_PLAN_ERROR',{weeklyState:'error',weeklyClientRejected:true},{weeklyStub:'error'}).status,'OBSERVED'));
const goodInteraction={name:'PWA_MODAL_OPEN_CLOSE',targetFound:true,targetVisible:true,actionDispatched:true,expectedStateObserved:true,closed:true,focusRestored:true};
test('FULL_INTERACTION depende de transição comprovada',()=>assert.equal(observed('FULL_INTERACTION',{}, {interactionResult:validateInteraction(goodInteraction)}).status,'OBSERVED'));
for(const [label,key] of [['botão ausente','targetFound'],['botão invisível','targetVisible'],['modal não abriu','expectedStateObserved'],['fechamento não ocorreu','closed'],['foco não restaurado','focusRestored']])test(label,()=>assert.equal(validateInteraction({...goodInteraction,[key]:false}).status,'FAILED'));
test('origem externa é recusada por host ou porta antes do envio',()=>{assert.equal(allowedRequest('http://127.0.0.1:123/a',123),true);assert.equal(allowedRequest('http://127.0.0.1:124/a',123),false);assert.equal(allowedRequest('https://127.0.0.1:123/a',123),false)});
const fakeCdp=failed=>({send:async method=>{if(method===failed)throw Object.assign(Error('secret detail'),{code:'CDP_FAIL'})}});
for(const method of ['CSS.stopRuleUsageTracking','Profiler.stopPreciseCoverage','Fetch.disable'])test(`cleanup registra falha real de ${method}`,async()=>{const c=await cleanupCdp(fakeCdp(method),{css:true,profiler:true,pausedRequests:new Set(),handlers:[]});assert.equal(c.errors.some(x=>x.step===method),true);assert.equal(c[method.startsWith('CSS')?'cssStopped':method.startsWith('Profiler')?'profilerStopped':'fetchDisabled'],false)});
test('target close falho não pode ser marcado concluído',async()=>{const closeTarget=async()=>{throw Error('fail')};await assert.rejects(closeTarget);assert.equal(false,false)});
test('proveniência separa head real e merge-ref',()=>{const head='1'.repeat(40),merge='2'.repeat(40);const source=buildSource({PERFORMANCE_HEAD_SHA:head,PERFORMANCE_CHECKOUT_SHA:merge,PERFORMANCE_WORKFLOW_SHA:merge,PERFORMANCE_BASE_SHA:'2281d6ed6fa2fad1303c45c25b5c1eb382011da6',PERFORMANCE_EVENT_NAME:'pull_request',PERFORMANCE_REF:'refs/pull/402/merge'},merge);assert.equal(source.headSha,head);assert.equal(source.checkoutSha,merge)});
const freqRuns=[1,2,3].map(run=>({run,state:'HOME_DEFAULT',scenario:'COLD',viewport:{name:'mobile'},javascriptCoverage:[{stableId:'/x.js',classification:'PORTAL_EXTERNAL',observedCodeUnits:run===3?0:2},{stableId:'/x.js',classification:'PORTAL_EXTERNAL',observedCodeUnits:2}]}));
test('frequência usa runs distintas apesar de múltiplas entradas',()=>{const x=frequencyByState(freqRuns,'javascript')[0];assert.equal(x.appearances,6);assert.equal(x.distinctRunsObserved,3);assert.equal(x.distinctRunsUsed,3);assert.equal(x.observationFrequency,1)});
test('frequência de uso não arredonda',()=>{const r=structuredClone(freqRuns);r[2].javascriptCoverage=[{stableId:'/x.js',classification:'PORTAL_EXTERNAL',observedCodeUnits:0}];assert.equal(frequencyByState(r,'javascript')[0].usageFrequency,2/3)});
test('script inline real usa metadados e identificador estável',()=>{const m={url:'',startLine:4,startColumn:1,endLine:8,endColumn:2};assert.equal(classifyScript(m),'PORTAL_INLINE');assert.match(scriptStableId(m,'PORTAL_INLINE'),/#inline-4-1-8-2$/)});
test('instrumentação LAB e Chrome são excluíveis',()=>{assert.equal(classifyScript({url:'portal-lab://instrumentation'}),'LAB_INSTRUMENTATION');assert.equal(classifyScript({url:'chrome-extension://x'}),'INTERNAL_CHROME')});
test('varredura rejeita dado sensível em qualquer parte do relatório',()=>assert.throws(()=>scanArtifact({runs:[{nested:'Bearer abc'}]}),/SENSITIVE_ARTIFACT/));
const matrixRuns=[];for(const state of profile.states)for(const viewport of profile.viewports)for(let run=1;run<=profile.runs;run++)for(const scenario of profile.scenarios)matrixRuns.push({state,scenario,viewport,run});
test('matriz contém exatamente 96 combinações',()=>{assert.equal(expectedRunIds(profile).length,96);assert.equal(validateRunMatrix(matrixRuns,profile).valid,true)});
test('combinação duplicada é recusada',()=>assert.equal(validateRunMatrix([...matrixRuns,matrixRuns[0]],profile).valid,false));
test('combinação ausente é recusada',()=>assert.equal(validateRunMatrix(matrixRuns.slice(1),profile).valid,false));
test('análise recusa relatório inválido',()=>assert.throws(()=>validateReport({schemaVersion:'1.0.0',environment:'LAB_STUBBED',optimizationAuthorized:false,runs:[],profile}),/REPORT_MATRIX_INVALID/));
test('optimizationAuthorized true é sempre recusado',()=>assert.throws(()=>validateReport({schemaVersion:'1.0.0',environment:'LAB_STUBBED',optimizationAuthorized:true,runs:[],profile}),/REPORT_CONTRACT_INVALID/));


test('origem exata exige mesma porta',()=>{const o='http://127.0.0.1:43123';assert.equal(isAllowedOrigin('http://127.0.0.1:43123/portal.css',o),true);assert.equal(isAllowedOrigin('http://127.0.0.1:43124/portal.css',o),false)});
test('localhost, 0.0.0.0, IPv6 e protocolo diferente são externos',()=>{const o='http://127.0.0.1:43123';for(const u of ['http://localhost:43123/x','http://0.0.0.0:43123/x','http://[::1]:43123/x','https://127.0.0.1:43123/x'])assert.equal(isAllowedOrigin(u,o),false)});
test('URL com credenciais nunca é permitida',()=>assert.equal(isAllowedOrigin('http://user:pass@127.0.0.1:43123/x','http://127.0.0.1:43123'),false));
test('origem autorizada precisa de HTTP, loopback e porta explícita',()=>{for(const o of ['http://127.0.0.1','https://127.0.0.1:1','http://localhost:1','http://user@127.0.0.1:1'])assert.equal(isAllowedOrigin('http://127.0.0.1:1/x',o),false)});
test('recurso local perde query e fragmento',()=>assert.equal(sanitizeLocalResourceUrl('http://127.0.0.1:43123/portal.css?private=x#frag','http://127.0.0.1:43123'),'/portal.css'));
test('externo preserva apenas marcador e pathname',()=>assert.equal(sanitizeBlockedExternalUrl('http://127.0.0.1:43124/outside.js?private=x#frag','http://127.0.0.1:43123'),'[EXTERNAL]/outside.js'));
test('URL externa inválida tem representação determinística',()=>assert.equal(sanitizeBlockedExternalUrl('not a url','http://127.0.0.1:43123'),'[EXTERNAL]'));
test('tentativa externa torna run FAILED',()=>{const externalRequests=[{url:'[EXTERNAL]/outside.js',blockedBeforeSend:true}];assert.equal(externalRequests.length===0?'MEASURED':'FAILED','FAILED')});


test('HOME_DEFAULT sai de loading pelo contrato real',()=>assert.equal(observed('HOME_DEFAULT',{pushState:'waiting',pushBusy:false}).status,'OBSERVED'));
test('HOME_DEFAULT com promise pendente permanece NOT_OBSERVED',()=>assert.equal(observed('HOME_DEFAULT',{pushState:'loading',pushBusy:true}).status,'NOT_OBSERVED'));
test('propriedade undefined continua presente no operador in',()=>{const x={PushManager:undefined};assert.equal('PushManager'in x,true)});
test('delete remove realmente a propriedade',()=>{const x={PushManager:undefined};assert.equal(delete x.PushManager,true);assert.equal('PushManager'in x,false)});
test('PUSH_UNSUPPORTED exige precondição de remoção',()=>assert.equal(observed('PUSH_UNSUPPORTED',{pushApiAvailable:false,pushState:'unsupported',pushButtonDisabled:true,pushManagerPresent:true,unsupportedPrecondition:false}).status,'NOT_OBSERVED'));
test('WEEKLY_PLAN_ERROR exige rejeição controlada do cliente após HTTP 200',()=>assert.equal(observed('WEEKLY_PLAN_ERROR',{weeklyState:'error',weeklyClientRejected:true},{weeklyStub:'error'}).status,'OBSERVED'));
test('envelope vazio continua empty e não error',()=>{assert.equal(observed('WEEKLY_PLAN_EMPTY',{weeklyState:'empty'},{weeklyStub:'empty'}).status,'OBSERVED');assert.equal(observed('WEEKLY_PLAN_ERROR',{weeklyState:'empty'},{weeklyStub:'error'}).status,'NOT_OBSERVED')});
const js=(ranges,length=100)=>summarizeJavaScriptCoverage([{ranges}],length);
test('JS pai usado e filho não usado desconta filho',()=>assert.deepEqual({...js([{startOffset:0,endOffset:100,count:1},{startOffset:20,endOffset:30,count:0}]),observedSegments:undefined},{sourceLength:100,observedCodeUnits:90,notObservedCodeUnits:10,observedPercent:90,observedSegments:undefined}));
test('JS pai não usado e filho usado observa somente filho',()=>{const x=js([{startOffset:0,endOffset:100,count:0},{startOffset:20,endOffset:30,count:1}]);assert.equal(x.observedCodeUnits,10);assert.equal(x.notObservedCodeUnits,90)});
test('JS três níveis usa o range mais específico',()=>{const x=js([{startOffset:0,endOffset:100,count:1},{startOffset:10,endOffset:90,count:0},{startOffset:20,endOffset:30,count:1}]);assert.equal(x.observedCodeUnits,30)});
test('JS irmãos usados e não usados são disjuntos',()=>{const x=js([{startOffset:0,endOffset:100,count:0},{startOffset:0,endOffset:20,count:1},{startOffset:20,endOffset:40,count:0},{startOffset:40,endOffset:60,count:1}]);assert.equal(x.observedCodeUnits,40)});
test('JS ranges cruzados são bloqueados',()=>assert.throws(()=>js([{startOffset:0,endOffset:60,count:1},{startOffset:40,endOffset:80,count:0}]),/CROSS/));
test('JS count negativo e não inteiro são bloqueados',()=>{assert.throws(()=>js([{startOffset:0,endOffset:1,count:-1}]),/INVALID/);assert.throws(()=>js([{startOffset:0,endOffset:1,count:.5}]),/INVALID/)});
test('JS sourceLength zero e null preservam contrato',()=>{assert.equal(js([],0).observedPercent,null);assert.equal(summarizeJavaScriptCoverage([],null).observedCodeUnits,null)});
test('JS UTF-16 mede surrogate pair em code units',()=>assert.equal(js([{startOffset:0,endOffset:2,count:1}],2).observedCodeUnits,2));
test('JS mantém invariante observado mais não observado',()=>{const x=js([{startOffset:0,endOffset:100,count:1},{startOffset:5,endOffset:7,count:0}]);assert.equal(x.observedCodeUnits+x.notObservedCodeUnits,x.sourceLength);assert.equal(x.observedPercent,x.observedCodeUnits/x.sourceLength*100)});
test('JS permite 100% legítimo',()=>assert.equal(js([{startOffset:0,endOffset:100,count:1}]).observedPercent,100));
test('JS impede falso 100% quando filho efetivo tem count zero',()=>assert.notEqual(js([{startOffset:0,endOffset:100,count:1},{startOffset:20,endOffset:30,count:0}]).observedPercent,100));
test('CSS mantém semântica de união simples de regras usadas',()=>assert.equal(summarizeCssCoverage([{startOffset:0,endOffset:20,used:true},{startOffset:10,endOffset:30,used:true}],100).observedCodeUnits,30));
test('múltiplas funções JS usam especificidade global',()=>{const x=summarizeJavaScriptCoverage([{ranges:[{startOffset:0,endOffset:100,count:1}]},{ranges:[{startOffset:20,endOffset:40,count:0}]}],100);assert.equal(x.observedCodeUnits,80)});
test('resumo determinístico agrega falhas por estado',()=>{const errors=summarizeReportErrors([{state:'HOME_DEFAULT',scenario:'COLD',viewport:{name:'mobile'},run:1,completionStatus:'FAILED',stateValidation:{status:'NOT_OBSERVED'}},{state:'HOME_DEFAULT',scenario:'WARM',viewport:{name:'mobile'},run:1,completionStatus:'FAILED',stateValidation:{status:'NOT_OBSERVED'}}]);assert.deepEqual(errors,[{code:'STATE_NOT_OBSERVED',state:'HOME_DEFAULT',failedRuns:2,combinations:['HOME_DEFAULT|COLD|mobile|1','HOME_DEFAULT|WARM|mobile|1']}])});
test('análise FAILED é diagnóstica sem rankings',()=>assert.deepEqual(failedAnalysis({status:'FAILED',errors:[{code:'STATE_NOT_OBSERVED'}]}),{schemaVersion:'1.0.0',environment:'LAB_STUBBED',status:'FAILED',sourceStatus:'FAILED',errors:[{code:'STATE_NOT_OBSERVED'}],rankings:{},optimizationAuthorized:false}));
test('JSON inválido com HTTP 200 rejeita parsing controladamente',async()=>{const response=new Response('{',{status:200,headers:{'content-type':'application/json'}});assert.equal(response.status,200);await assert.rejects(response.json())});
