import test from 'node:test';import assert from 'node:assert/strict';
import {analyzePerformanceReport,analysisMarkdown,delta,sanitizeSelector,validatePerformanceReport} from '../scripts/lib/portal-performance-analysis.mjs';
import {startLocalServer} from '../scripts/lib/portal-performance-server.mjs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const pages=['/portal-login.html','/portal-premium-home.html','/portal-checkin.html','/portal-plano-alimentar.html','/portal-progressao.html'];const metrics=['ttfb','fcp','lcp','cls','domContentLoaded','load','longTaskCount','longTaskDuration','requestCount','apiRequestCount','failedRequestCount','transferBytes','encodedBodyBytes','decodedBodyBytes'];
function fixture(status='MEASURED'){const source={sha:'a4c7e6e49a2f0c6df3a6ffb884934da156fe240a',repositorySha:'a4c7e6e49a2f0c6df3a6ffb884934da156fe240a',workflowSha:'04741d6d7a1848e11afecee2f132fa92283ff1a5',measuredSha:'a4c7e6e49a2f0c6df3a6ffb884934da156fe240a',ref:'refs/heads/main',eventName:'workflow_dispatch',nodeVersion:'v22',chromeVersion:'Chrome/150'};const runStatus=status;const mk=(page,scenario,i)=>{const m=Object.fromEntries(metrics.map(k=>[k,k==='cls'&&page.includes('home')&&scenario==='COLD'?.33:k==='failedRequestCount'?0:k==='longTaskCount'||k==='longTaskDuration'?0:scenario==='COLD'?100:50]));return{run:i,page,scenario,metrics:m,resources:[{url:'/portal.css',type:'stylesheet',transferBytes:73,decodedBodyBytes:100,fromCache:scenario==='WARM',status:200}],failedRequests:[],layoutShiftEvents:page.includes('home')&&scenario==='COLD'?[{startTime:i,value:.33,hadRecentInput:false,sources:i===5?null:[{nodeSelector:'main>div.card',previousRect:null,currentRect:null}]}]:[],completionStatus:runStatus}};const ps=pages.map(page=>({page,scenarios:['COLD','WARM'].map(scenario=>{const runs=Array.from({length:5},(_,i)=>mk(page,scenario,i+1));const aggregate=Object.fromEntries(metrics.map(k=>[k,{median:runs[0].metrics[k],p75:runs[0].metrics[k]}]));return{scenario,runs,aggregate}})}));return{schemaVersion:'1.0.0',environment:'LAB_STUBBED',source,profile:{schemaVersion:'1.0.0',runs:5,scenarios:['COLD','WARM'],pages,viewport:{},network:{},cpuSlowdownMultiplier:1},pages:ps,warnings:[],status}}
test('relatório válido, source main distinto de merge ref e Markdown determinístico',()=>{const r=fixture();assert.equal(validatePerformanceReport(r),r);const a=analyzePerformanceReport(r);assert.equal(a.validity.runs,50);assert.notEqual(a.source.repositorySha,a.source.workflowSha);assert.equal(analysisMarkdown(a),analysisMarkdown(a));assert.match(analysisMarkdown(a),/Nenhuma otimização/)});
test('INCOMPLETE e FAILED válidos quando coerentes; HTTP 404 vira P0',()=>{for(const s of ['INCOMPLETE','FAILED'])assert.equal(analyzePerformanceReport(fixture(s)).status,s);const r=fixture('INCOMPLETE');const run=r.pages[0].scenarios[0].runs[0];run.failedRequests=[{url:'/api/x',status:404}];run.metrics.failedRequestCount=1;assert.ok(analyzePerformanceReport(r).findings.some(x=>x.priority==='P0'&&x.actual===404))});
test('página, cenário e run ausentes falham',()=>{for(const mutate of [r=>r.pages.pop(),r=>r.pages[0].scenarios.pop(),r=>r.pages[0].scenarios[0].runs.pop()]){const r=fixture();mutate(r);assert.throws(()=>validatePerformanceReport(r),/inválido/)}});
test('null opcional, deltas e divisão por zero',()=>{const r=fixture();r.pages[0].scenarios[0].runs[0].metrics.lcp=null;assert.doesNotThrow(()=>validatePerformanceReport(r));assert.deepEqual(delta(100,50),{absolute:50,percentage:100});assert.deepEqual(delta(5,0),{absolute:5,percentage:null})});
test('ranking/compartilhamento/cache são determinísticos e não recomendam remoção',()=>{const a=analyzePerformanceReport(fixture());assert.ok(a.resources.every(x=>x.pagesPresent.length===5&&x.removalAuthorized===false));assert.ok(a.resources.some(x=>x.fromCache===5));assert.deepEqual(a.resources,[...a.resources].sort((x,y)=>x.page.localeCompare(y.page)||x.scenario.localeCompare(y.scenario)||(y.transferBytes??-1)-(x.transferBytes??-1)||x.url.localeCompare(y.url)))});
test('CLS repetível é P1; múltiplos shifts, sources null e contribuição ordenada',()=>{const a=analyzePerformanceReport(fixture());assert.ok(a.findings.some(x=>x.metric==='cls'&&x.priority==='P1'));assert.equal(a.layoutShiftElements[0].count,4);assert.equal(a.layoutShiftElements[0].contribution,1.32);assert.match(analysisMarkdown(a),/sources não disponibilizadas|null/)});
test('seletor remove atributos sensíveis e limita classes/caminho',()=>{const x=sanitizeSelector({tag:'DIV',id:'student-email',classes:['safe','token-value','also','extra'],parents:[{tag:'body'},{tag:'main',id:'root'}]});assert.equal(x,'body>main#root>div.safe.also');assert.doesNotMatch(x,/student|email|token|extra/)});
test('stub confirma GET count zero, método e desconhecido',async()=>{const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../public');const s=await startLocalServer(root);try{const base=`http://127.0.0.1:${s.port}`;let response=await fetch(base+'/api/portal/notifications/unread-count');assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,data:{count:0}});response=await fetch(base+'/api/portal/notifications/unread-count',{method:'POST'});assert.equal(response.status,405);response=await fetch(base+'/api/unknown');assert.equal(response.status,404);assert.doesNotMatch(JSON.stringify(s.requests),/@|token|Aluno/)}finally{await s.close()}});
