import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { createObjectives, EXPECTED_AFTER_DECISION, runPremiumObjectivesSmoke, validateDecision, validateObjectivesReload, validateObjectivesSave, validatePremiumObjectivesCalls } from '../scripts/qa-premium-objectives-staging-e2e.mjs';

const env={QA_BASE_URL:'https://preview.example.test',QA_TARGET_ENVIRONMENT:'staging',QA_ADMIN_SESSION:'admin-secret',GITHUB_RUN_ID:'417',GITHUB_RUN_ATTEMPT:'1'};
const studentId='student-f17', token='student-secret', anamnesisId='anam-f17', marker='QA-F1.7-417-1';
const response=(status,body,ok=status>=200&&status<300)=>({ok,status,responseBody:JSON.stringify(body),durationMs:1});
function fake(change={}) { let access=0, objectives=null; const calls=[]; return {calls,requestFn:async(path,options={})=>{calls.push({path,options});
  if(path==='/api/admin/premium/workspace/students')return response(201,{ok:true,data:{studentId,email:options.body.email,status:'AWAITING_ANAMNESIS',accessLink:`${env.QA_BASE_URL}/portal-login.html`,token}});
  if(path==='/api/portal/login')return response(200,{ok:true,data:{email:options.body.email,plan:'premium'}});
  if(path==='/api/anamnese-premium')return response(200,{ok:true,data:{id:anamnesisId,alreadySubmitted:false}});
  if(path==='/api/portal/premium/access-state'){access++;const lifecycle=access===1?'AWAITING_ANAMNESIS':access===2?(change.beforeLifecycle||'UNDER_REVIEW'):(change.afterLifecycle||EXPECTED_AFTER_DECISION);return response(200,{ok:true,data:{consultationStatus:lifecycle,primaryAction:lifecycle==='AWAITING_ANAMNESIS'?{href:'/anamnese-premium.html'}:null}});}
  if(path.endsWith('/record'))return response(200,{ok:true,data:{student:{student_id:change.recordStudentId||studentId},anamnesis:{id:anamnesisId,student_id:studentId,created_at:'now',report:{marker}}}});
  if(path.endsWith('/planning-objectives')){if((options.method||'GET')==='PUT'){if(change.save)return change.save;objectives={id:'plan-1',student_id:studentId,status:'ACTIVE',...options.body};return response(200,{ok:true,data:objectives});}if(!objectives)return response(200,{ok:true,data:{student_id:studentId,status:'EMPTY',training_focus:'',cardio_target:'',nutrition_focus:'',main_risk:'',coach_message:''}});const loaded=change.reload||objectives;return response(200,{ok:true,data:loaded});}
  if(path.endsWith('/status'))return change.decision||response(200,{ok:true,data:{student_id:studentId,from:'UNDER_REVIEW',to:'READY_TO_RELEASE',updated_at:'now',followup_entry_id:'followup-1'}});
  throw new Error(`unexpected ${path}`);
  }};
}

test('valid fixture, five-field save, independent reload, decision and lifecycle validate F1.7',async()=>{const api=fake(),masked=[];const report=await runPremiumObjectivesSmoke({env,requestFn:api.requestFn,mask:x=>masked.push(x)});assert.equal(report.status,'VALIDATED');assert.deepEqual(report.rows.map(x=>x.flow),['fixture-under-review','student-record-pre-decision','objectives-save','objectives-persistence','professional-decision','lifecycle-after-decision','identity-consistency','project-lm-isolation']);assert.ok(masked.includes(token)&&masked.includes(env.QA_ADMIN_SESSION));assert.doesNotMatch(JSON.stringify(report),/student-secret|admin-secret|@example\.test/i);});
test('canonical payload contains a unique marker in all real fields',()=>{const value=createObjectives('MARK');assert.deepEqual(Object.keys(value),['training_focus','cardio_target','nutrition_focus','main_risk','coach_message']);assert.ok(Object.values(value).every(x=>x.includes('MARK')));});
test('save rejects 4xx, HTTP 200 ok:false, wrong identity and false response echo',()=>{const expected=createObjectives(marker), good={ok:true,data:{student_id:studentId,...expected}};assert.equal(validateObjectivesSave(response(200,good),expected,studentId).ok,true);assert.equal(validateObjectivesSave(response(400,{ok:false},false),expected,studentId).ok,false);assert.equal(validateObjectivesSave(response(200,{ok:false}),expected,studentId).ok,false);assert.equal(validateObjectivesSave(response(200,{ok:true,data:{student_id:'other',...expected}}),expected,studentId).ok,false);assert.equal(validateObjectivesSave(response(200,{ok:true,data:{student_id:studentId,...expected,main_risk:'wrong'}}),expected,studentId).ok,false);});
test('reload proves exact persistence and rejects absent marker or divergent studentId',()=>{const expected=createObjectives(marker), good=response(200,{ok:true,data:{student_id:studentId,...expected}});assert.equal(validateObjectivesReload(good,expected,studentId).ok,true);assert.equal(validateObjectivesReload(response(200,{ok:true,data:{student_id:studentId,...expected,coach_message:'lost'}}),expected,studentId).ok,false);assert.equal(validateObjectivesReload(response(200,{ok:true,data:{student_id:'other',...expected}}),expected,studentId).ok,false);});
test('decision validates real response and lifecycle divergence fails closed',async()=>{assert.equal(validateDecision(response(200,{ok:true,data:{student_id:studentId,from:'UNDER_REVIEW',to:'READY_TO_RELEASE',followup_entry_id:'f1'}}),studentId).ok,true);assert.equal(validateDecision(response(200,{ok:false}),studentId).ok,false);assert.equal((await runPremiumObjectivesSmoke({env,requestFn:fake({afterLifecycle:'UNDER_REVIEW'}).requestFn})).status,'NOT_VALIDATED');});
test('status transition has no objective precondition and repeated objective PUT updates the same weekly row',async()=>{const api=fake();const endpoint=`/api/admin/premium/students/${studentId}/planning-objectives`, payload=createObjectives(marker);const first=await api.requestFn(endpoint,{method:'PUT',body:payload});const second=await api.requestFn(endpoint,{method:'PUT',body:payload});assert.equal(JSON.parse(first.responseBody).data.id,JSON.parse(second.responseBody).data.id);assert.equal(validateDecision(await api.requestFn(`/api/admin/premium/students/${studentId}/status`,{method:'PATCH',body:{status:'READY_TO_RELEASE'}}),studentId).ok,true);});
test('allowlist rejects Projeto LM, LM2 and check-in routes',()=>{assert.equal(validatePremiumObjectivesCalls([{method:'PUT',path:`/api/admin/premium/students/${studentId}/planning-objectives`}]).ok,true);for(const path of ['/api/project-lm/victories','/api/project-lm-2/checkin','/api/portal/checkin'])assert.equal(validatePremiumObjectivesCalls([{method:'POST',path}]).ok,false);});
test('workflow orders F1.7 after F1.6, uses pipefail tee, and uploads report',async()=>{const workflow=await readFile('.github/workflows/qa-lm-staging.yml','utf8');assert.ok(workflow.indexOf('npm run qa:lm:premium-objectives')>workflow.indexOf('npm run qa:lm:premium-anamnesis'));assert.match(workflow,/set -o pipefail\n\s+npm run qa:lm:premium-objectives \| tee qa-premium-objectives-report\.json/);assert.match(workflow,/qa-premium-objectives-report\.json/);});
test('NOT_VALIDATED exits 1 through a pipefail tee pipeline',async()=>{const child=spawn('bash',['-o','pipefail','-c','node scripts/qa-premium-objectives-staging-e2e.mjs | tee /dev/null'],{env:{...process.env,QA_BASE_URL:env.QA_BASE_URL,QA_TARGET_ENVIRONMENT:'staging',QA_ADMIN_SESSION:''},stdio:['ignore','pipe','pipe']});let out='';child.stdout.on('data',x=>out+=x);const [code]=await once(child,'exit');assert.equal(code,1);assert.match(out,/NOT_VALIDATED/);});
