import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { PREMIUM_NUTRITION_PLAN_CALLS, validateDraft, validatePremiumNutritionPlanCalls, validatePreReleaseStudentPlan, validateProfessionalCurrent, validatePublish, validateRelease, validateReleasedLifecycle, validateStudentPlan, validateWrite } from '../scripts/qa-premium-nutrition-plan-staging-e2e.mjs';

const result=(body,status=200)=>({ok:status>=200&&status<300,status,responseBody:JSON.stringify(body)});
const studentId='student-1', planId='plan-1', marker='QA-F1.8-run-1', editedMarker=`${marker}-EDITADO`, deletedMarker=`${marker}-EXCLUIR`;
// Exact admin presenter shape returned by POST create (and by GET/PATCH): the
// repository stores is_active=0, but the HTTP contract does not expose the field.
const draft={id:planId,student_id:studentId,student_email:'student@example.test',title:'Plano alimentar',goal:'',strategy:'',meals:[],substitutions:[],adherence_rules:[],notes:'',whatsapp_message:'',status:'DRAFT',version_number:null,published_at:null,published_by:null,archived_at:null,supersedes_plan_id:null,source_feedback_id:null,created_at:'2026-08-10T00:00:00Z',updated_at:'2026-08-10T00:00:00Z'};
const meals=[{id:'meal-1',name:'Café da manhã',guidance:editedMarker,items:[{food:marker,quantity:'1',unit:'unidade'}]},{id:'meal-2',name:'Almoço',primary_text:marker,items:[]}];

test('draft creation accepts the real admin presenter contract without is_active',()=>{assert.equal(Object.hasOwn(draft,'is_active'),false);assert.equal(validateDraft(result({ok:true,data:draft}),studentId).ok,true);});
test('draft response without id fails closed',()=>assert.equal(validateDraft(result({ok:true,data:Object.fromEntries(Object.entries(draft).filter(([key])=>key!=='id'))}),studentId).ok,false));
test('draft response with undefined id fails closed',()=>assert.equal(validateDraft(result({ok:true,data:{...draft,id:undefined}}),studentId).ok,false));
test('draft response with null id fails closed',()=>assert.equal(validateDraft(result({ok:true,data:{...draft,id:null}}),studentId).ok,false));
test('draft response with MouseEvent id fails closed',()=>assert.equal(validateDraft(result({ok:true,data:{...draft,id:'[object MouseEvent]'}}),studentId).ok,false));
test('unexpected draft status fails closed',()=>assert.equal(validateDraft(result({ok:true,data:{...draft,status:'PUBLISHED'}}),studentId).ok,false));
test('HTTP 200 with ok false is not a draft creation success',()=>assert.equal(validateDraft(result({ok:false,data:draft}),studentId).ok,false));
test('draft creation HTTP 4xx fails closed',()=>assert.equal(validateDraft(result({ok:false,data:draft},409),studentId).ok,false));
test('meal write accepts canonical persisted meal contract',()=>assert.equal(validateWrite(result({ok:true,data:{...draft,meals}}),{planId,studentId,marker}).ok,true));
test('meal without id is rejected by the operational contract',()=>assert.ok(!meals.map(x=>x.id).concat([null]).every(id=>id&&!['undefined','null','[object MouseEvent]'].includes(String(id)))));
test('structured item keeps food, quantity and unit',()=>assert.deepEqual(meals[0].items[0],{food:marker,quantity:'1',unit:'unidade'}));
test('independent reload validator requires marker persistence',()=>assert.equal(validateWrite(result({ok:true,data:{...draft,meals}}),{planId,studentId,marker}).ok,true));
test('edit validator requires edited marker',()=>assert.equal(validateWrite(result({ok:true,data:{...draft,meals}}),{planId,studentId,marker,editedMarker}).ok,true));
test('delete validator rejects the disposable marker while retaining content',()=>assert.equal(validateWrite(result({ok:true,data:{...draft,meals}}),{planId,studentId,marker,deletedMarker}).ok,true));
const published={...draft,status:'PUBLISHED',version_number:1,published_at:'2026-08-10T01:00:00Z',published_by:'admin',meals};
test('publication accepts the real admin presenter contract without is_active',()=>{assert.equal(Object.hasOwn(published,'is_active'),false);assert.equal(validatePublish(result({ok:true,data:published}),{planId,studentId}).ok,true);});
for (const [label,id] of [['missing',undefined],['undefined',undefined],['null',null],['MouseEvent','[object MouseEvent]']]) test(`publish ${label} id fails closed`,()=>{const plan={...published,id};if(label==='missing')delete plan.id;assert.equal(validatePublish(result({ok:true,data:plan}),{planId,studentId}).ok,false);});
test('publish studentId divergence fails closed',()=>assert.equal(validatePublish(result({ok:true,data:published}),{planId,studentId:'other'}).ok,false));
test('publish DRAFT status fails closed',()=>assert.equal(validatePublish(result({ok:true,data:{...published,status:'DRAFT'}}),{planId,studentId}).ok,false));
test('publish missing version_number fails closed',()=>{const plan={...published};delete plan.version_number;assert.equal(validatePublish(result({ok:true,data:plan}),{planId,studentId}).ok,false);});
test('publish version_number zero fails closed',()=>assert.equal(validatePublish(result({ok:true,data:{...published,version_number:0}}),{planId,studentId}).ok,false));
test('publish 4xx fails closed',()=>assert.equal(validatePublish(result({ok:false},409),{planId,studentId}).ok,false));
test('HTTP 200 with ok false is not a publication success',()=>assert.equal(validatePublish(result({ok:false,data:published}),{planId,studentId}).ok,false));
const workflow=current=>result({ok:true,data:{current,draft:null}});
test('professional current independently proves activation and published content',()=>assert.equal(validateProfessionalCurrent(workflow(published),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,true));
test('professional current fails when current is null',()=>assert.equal(validateProfessionalCurrent(workflow(null),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,false));
test('professional current fails for another plan id',()=>assert.equal(validateProfessionalCurrent(workflow({...published,id:'other'}),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,false));
test('professional current fails unless status is PUBLISHED',()=>assert.equal(validateProfessionalCurrent(workflow({...published,status:'ARCHIVED'}),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,false));
test('professional current fails when draft remains',()=>assert.equal(validateProfessionalCurrent(result({ok:true,data:{current:published,draft}}),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,false));
test('professional current fails when published marker diverges',()=>assert.equal(validateProfessionalCurrent(workflow({...published,meals:[]}),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,false));
test('professional current requires the version returned by publish',()=>assert.equal(validateProfessionalCurrent(workflow({...published,version_number:2}),{planId,studentId,version:1,marker,editedMarker,deletedMarker}).ok,false));
test('student unauthenticated read contract is explicitly 401',()=>assert.match(fs.readFileSync('scripts/qa-premium-nutrition-plan-staging-e2e.mjs','utf8'),/expectedStatus:\[401\]/));
test('published plan remains forbidden before consultation release',()=>assert.equal(validatePreReleaseStudentPlan(result({ok:false,error:'locked'},403)).ok,true));
test('pre-release validator does not accept an early 200',()=>assert.equal(validatePreReleaseStudentPlan(result({ok:true,data:published})).ok,false));
const release={student_id:studentId,from:'READY_TO_RELEASE',to:'ACTIVE',updated_at:'2026-08-10T02:00:00Z',followup_entry_id:'followup-1'};
test('professional release requires the exact identity and lifecycle transition',()=>assert.equal(validateRelease(result({ok:true,data:release}),{studentId}).ok,true));
test('release ok false fails closed',()=>assert.equal(validateRelease(result({ok:false,data:release}),{studentId}).ok,false));
test('release 4xx fails closed',()=>assert.equal(validateRelease(result({ok:false},409),{studentId}).ok,false));
test('release studentId divergence fails closed',()=>assert.equal(validateRelease(result({ok:true,data:release}),{studentId:'other'}).ok,false));
test('release from divergence fails closed',()=>assert.equal(validateRelease(result({ok:true,data:{...release,from:'UNDER_REVIEW'}}),{studentId}).ok,false));
test('release to divergence fails closed',()=>assert.equal(validateRelease(result({ok:true,data:{...release,to:'PAUSED'}}),{studentId}).ok,false));
test('idempotent unchanged response is not accepted as release evidence',()=>assert.equal(validateRelease(result({ok:true,data:{...release,from:'ACTIVE',unchanged:true}}),{studentId}).ok,false));
const activeState={consultationStatus:'ACTIVE',experience:'PREMIUM_PORTAL'};
test('lifecycle reload confirms ACTIVE for the released identity',()=>assert.equal(validateReleasedLifecycle(result({ok:true,data:activeState}),{studentId,releaseStudentId:studentId}).ok,true));
test('lifecycle reload rejects READY_TO_RELEASE',()=>assert.equal(validateReleasedLifecycle(result({ok:true,data:{...activeState,consultationStatus:'READY_TO_RELEASE'}}),{studentId,releaseStudentId:studentId}).ok,false));
test('lifecycle reload rejects release identity divergence',()=>assert.equal(validateReleasedLifecycle(result({ok:true,data:activeState}),{studentId,releaseStudentId:'other'}).ok,false));
test('authenticated student receives exact published content',()=>assert.equal(validateStudentPlan(result({ok:true,data:{status:'PUBLISHED',version_number:1,meals}}),{marker,editedMarker,deletedMarker,version:1}).ok,true));
test('post-release 403 fails student consistency',()=>assert.equal(validateStudentPlan(result({ok:false},403),{marker,editedMarker,deletedMarker,version:1}).ok,false));
test('missing run marker fails student consistency',()=>assert.equal(validateStudentPlan(result({ok:true,data:{status:'PUBLISHED',version_number:1,meals:[]}}),{marker,editedMarker,deletedMarker,version:1}).ok,false));
test('wrong public version fails student consistency',()=>assert.equal(validateStudentPlan(result({ok:true,data:{status:'PUBLISHED',version_number:2,meals}}),{marker,editedMarker,deletedMarker,version:1}).ok,false));
test('draft exposed by public response fails student consistency',()=>assert.equal(validateStudentPlan(result({ok:true,data:{status:'DRAFT',version_number:1,meals}}),{marker,editedMarker,deletedMarker,version:1}).ok,false));
test('studentId divergence fails draft contract',()=>assert.equal(validateDraft(result({ok:true,data:draft}),'other').ok,false));
test('allowlist rejects Projeto LM and accepts only the explicit F1.8 routes',()=>{assert.equal(validatePremiumNutritionPlanCalls([{method:'GET',path:'/api/portal/project-lm/current-mission'}]).ok,false);assert.ok(PREMIUM_NUTRITION_PLAN_CALLS.has('GET /api/portal/nutrition-plan'));});
test('report source masks secrets and excludes email, token and session from evidence',()=>{const source=fs.readFileSync('scripts/qa-premium-nutrition-plan-staging-e2e.mjs','utf8');assert.match(source,/mask\(env\.QA_ADMIN_SESSION\)/);assert.match(source,/mask\(email\)/);assert.match(source,/mask\(token\)/);assert.doesNotMatch(source,/add\([^\n]*\{[^\n]*(?:email|token|session)/i);});
test('NOT_VALIDATED exits non-zero',()=>assert.match(fs.readFileSync('scripts/qa-premium-nutrition-plan-staging-e2e.mjs','utf8'),/report\.status==='VALIDATED'\?0:1/));
test('workflow preserves smoke failure through tee and uploads its report',()=>{const workflow=fs.readFileSync('.github/workflows/qa-lm-staging.yml','utf8');assert.match(workflow,/set -o pipefail\n\s+npm run qa:lm:premium-nutrition-plan \| tee qa-premium-nutrition-plan-report\.json/);assert.match(workflow,/qa-premium-nutrition-plan-report\.json/);});
test('PR 405 regression: UI meal selector feeds the selected type into the persisted model',()=>{const source=fs.readFileSync('public/admin-premium-nutrition-plan.js','utf8');assert.match(source,/const mealName=await openMealSelector\(\);if\(!mealName\)return;createMeal\(mealName\)/);assert.match(source,/m\.meals\.map\(meal=>/);});
test('PR 406 regression: edit and publish requests use a guarded canonical id',()=>{const source=fs.readFileSync('public/admin-premium-nutrition-plan.js','utf8');assert.match(source,/if\(!source\|\|typeof source!=='object'\|\|!source\.id\)/);assert.match(source,/encodeURIComponent\(source\.id\).*duplicate-as-draft/);assert.match(source,/const reviewedDraftId=state\.draft\.id/);assert.doesNotMatch(`/api/admin/premium/nutrition-plans/${planId}/draft`,/undefined|null|\[object MouseEvent\]/);});
