export const EVENT_TYPES = Object.freeze({
  ANAMNESE_SUBMITTED: 'ANAMNESE_SUBMITTED',
  CHECKIN_SUBMITTED: 'CHECKIN_SUBMITTED',
  PROGRESSION_LOG_SUBMITTED: 'PROGRESSION_LOG_SUBMITTED',
  STUDENT_INACTIVATED: 'STUDENT_INACTIVATED',
  STUDENT_REACTIVATED: 'STUDENT_REACTIVATED',
  REACTIVATION_CONTACT_SENT: 'REACTIVATION_CONTACT_SENT',
  FOLLOWUP_LOGGED: 'FOLLOWUP_LOGGED',
  WEEKLY_PLAN_UPDATED: 'WEEKLY_PLAN_UPDATED',
  NUTRITION_PLAN_UPDATED: 'NUTRITION_PLAN_UPDATED',
  COACH_REPLY_SENT: 'COACH_REPLY_SENT',
  STUDENT_TOKEN_UPDATED: 'STUDENT_TOKEN_UPDATED'
});
